# Generated by Django 2.1.11 on 2019-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20190722_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterHost', models.CharField(max_length=30)),
                ('dlHost', models.CharField(max_length=30)),
                ('uploadHost', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Hosts',
            },
        ),
    ]
