# Generated by Django 2.1.11 on 2019-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastJsCssStatus', models.IntegerField()),
                ('fastConsoleStatus', models.IntegerField()),
            ],
            options={
                'db_table': 'TestStatus',
            },
        ),
    ]
