# Generated by Django 2.1.11 on 2019-12-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_fastcheckdetail_jscsscheckinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jscsscheckinfo',
            old_name='endTiem',
            new_name='endTime',
        ),
    ]
