# Generated by Django 2.1.11 on 2019-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20191206_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jscsscheckinfo',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jscsscheckinfo',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
