# Generated by Django 2.1.11 on 2019-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20191206_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleCheckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorInfo', models.TextField()),
            ],
            options={
                'db_table': 'ConsoleCheckDetail',
            },
        ),
        migrations.CreateModel(
            name='ConsoleCheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('checkFileNum', models.IntegerField()),
                ('errorFileNum', models.IntegerField()),
                ('checkFile', models.TextField()),
            ],
            options={
                'db_table': 'ConsoleCheckInfo',
            },
        ),
    ]
