# Generated by Django 2.1.11 on 2020-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_auto_20191227_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('urlDescription', models.CharField(max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ConsoleUrl',
            },
        ),
    ]
