# Generated by Django 2.1.11 on 2020-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_consoleurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleErrorIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorContent', models.CharField(max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ConsoleErrorIgnore',
            },
        ),
    ]
