# Generated by Django 2.1.11 on 2020-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_consoleerrorignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=200)),
                ('functionStatus', models.IntegerField()),
            ],
            options={
                'db_table': 'FunctionTest',
            },
        ),
    ]
