# Generated by Django 2.1.11 on 2020-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_functiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='functiontest',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
