# Generated by Django 2.1.11 on 2020-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_functiontest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functiontest',
            name='testName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
